#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"

function usage {
  local NAME=$(basename $0)
  cat <<EOF
Usage: $NAME [options]

This script builds comet native binaries inside a docker image. The image is named
"comet-rm" and will be generated by this script

Options are:

  -d [path]   : working directory (copy the XCode sdk to this directory)
  -x          : XCode sdk file name
  -t [tag]    : tag for the spark-rm docker image to use for building (default: "latest").
EOF
}

MACOS_SDK_DIR=
MACOS_SDK=
HAS_MACOS_SDK="false"
IMGTAG=latest

while getopts "d:ht:" opt; do
  case $opt in
    d) MACOS_SDK_DIR="$OPTARG" ;;
    x) MACOS_SDK="$OPTARG" ;;
    t) IMGTAG="$OPTARG" ;;
    h) usage ;;
    \?) error "Invalid option. Run with -h for help." ;;
  esac
done

#docker buildx create --use --name cometbuild node-amd64
#docker buildx create --append --name cometbuild node-arm64

docker buildx create \
  --name comet-builder \
  --driver docker-container \
  --use --bootstrap

if [ -f "${MACOS_SDK_DIR}/${MACOS_SDK}" ]
then
  HAS_MACOS_SDK="true"
fi
docker buildx build \
  --no-cache \
  --platform linux/amd64,linux/arm64 \
  -t "comet-rm:$IMGTAG" \
  --build-arg UID=$UID \
  --build-arg HAS_MACOS_SDK=${HAS_MACOS_SDK} \
  --build-arg MACOS_SDK_DIR=${MACOS_SDK_DIR} \
  --build-arg MACOS_SDK=${MACOS_SDK} \
  --load \
  "$SCRIPT_DIR/comet-rm"

  # remove the builder
docker buildx rm --keep-state comet-builder
#docker build \
#  --no-cache \
#  --platform linux/amd64,linux/arm64 \
#  -t "comet-rm:$IMGTAG" \
#  --build-arg UID=$UID \
#  --build-arg HAS_MACOS_SDK=${HAS_MACOS_SDK} \
#  --build-arg MACOS_SDK_DIR=${MACOS_SDK_DIR} \
#  --build-arg MACOS_SDK=${MACOS_SDK} \
#  "$SCRIPT_DIR/comet-rm"

#docker build \
#  --no-cache \
#  --platform linux/arm64 \
#  -t "comet-rm:$IMGTAG" \
#  --build-arg UID=$UID \
#  --build-arg HAS_MACOS_SDK=${HAS_MACOS_SDK} \
#  --build-arg MACOS_SDK_DIR=${MACOS_SDK_DIR} \
#  --build-arg MACOS_SDK=${MACOS_SDK} \
#  "$SCRIPT_DIR/comet-rm"
#
#docker build \
#  --no-cache \
#  --platform linux/amd64 \
#  -t "comet-rm:$IMGTAG" \
#  --build-arg UID=$UID \
#  --build-arg HAS_MACOS_SDK=${HAS_MACOS_SDK} \
#  --build-arg MACOS_SDK_DIR=${MACOS_SDK_DIR} \
#  --build-arg MACOS_SDK=${MACOS_SDK} \
#  "$SCRIPT_DIR/comet-rm"

BUILDER_IMAGE=${BUILDER_IMAGE:='comet-rm:$IMGTAG'}

#docker pull --platform linux/amd64 ${BUILDER_IMAGE}
#docker pull --platform linux/arm64 ${BUILDER_IMAGE}

# docker run \
#    --memory 16g \
#    --cpus 6 \
#    -it \
#    --rm \
#    --platform linux/amd64 \
#    -v $WORKDIR:/mnt/workdir \
#    $BUILDER_IMAGE /bin/bash

# docker run \
#    --memory 16g \
#    --cpus 6 \
#    -it \
#    --rm \
#    --platform linux/arm64 \
#    -v $WORKDIR:/mnt/workdir \
#    $BUILDER_IMAGE /bin/bash

#docker run \
#   --memory 16g \
#   --cpus 6 \
#   -it \
#   --rm \
#   --platform linux/aarch64 \
#   -e APPLECONNECT_USER=${APPLECONNECT_USER} \
#   -e ARTIFACTORY_API_KEY=${ARTIFACTORY_API_KEY} \
#   -v ~/work/apple-parquet-mr:/mnt/parquet-mr \
#   -v ~/work/boson:/mnt/boson \
#   -v ~/work/spark/apache-spark:/mnt/spark \
#   -v ~/work/iceberg:/mnt/iceberg \
#   -v ~/work/spark/spark-perf:/mnt/spark-perf \
#   $BUILDER_IMAGE
