#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"

function usage {
  local NAME=$(basename $0)
  cat <<EOF
Usage: $NAME [options]

This script builds comet native binaries inside a docker image. The image is named
"comet-rm" and will be generated by this script

Options are:

  -r [repo]   : git repo
  -b [branch] : git branch
  -x          : XCode sdk file name
  -t [tag]    : tag for the spark-rm docker image to use for building (default: "latest").
EOF
exit 1
}

REPO="https://github.com/apache/datafusion-comet.git"
BRANCH="release"
MACOS_SDK=
HAS_MACOS_SDK="false"
IMGTAG=latest

while getopts "b:hr:t:x:" opt; do
  case $opt in
    r) REPO="$OPTARG";;
    b) BRANCH="$OPTARG";;
    x) MACOS_SDK="$OPTARG" ;;
    t) IMGTAG="$OPTARG" ;;
    h) usage ;;
    \?) error "Invalid option. Run with -h for help." ;;
  esac
done

WORKING_DIR="$SCRIPT_DIR/comet-rm/workdir"
cp $SCRIPT_DIR/../cargo.config $WORKING_DIR

# TODO: Search for Xcode
#PS3="Select Xcode:"
#select xcode_path in  `find . -name "Xcode*.xip"`
#do
#  echo "found Xcode in $xcode_path"
#  cp $xcode_path $WORKING_DIR
#  break
#done

if [ -f "${WORKING_DIR}/${MACOS_SDK}" ]
then
  HAS_MACOS_SDK="true"
fi

# Create docker builder context
docker buildx create \
  --name comet-builder \
  --driver docker-container \
  --use --bootstrap

# Build the docker image in which we will do the build
docker buildx build \
  --platform linux/amd64,linux/arm64 \
  -t "comet-rm:$IMGTAG" \
  --build-arg HAS_MACOS_SDK=${HAS_MACOS_SDK} \
  --build-arg MACOS_SDK=${MACOS_SDK} \
  --load \
  "$SCRIPT_DIR/comet-rm"

  # remove the builder
docker buildx rm --keep-state comet-builder

BUILDER_IMAGE="comet-rm:$IMGTAG"

# Run the builder container for each architecture . The entrypoint script will build the binaries and copy them to $WORKING_DIR/output

# AMD64
docker run \
   --memory 24g \
   --cpus 6 \
   -it \
   --rm \
   --platform linux/amd64 \
   -v $WORKING_DIR:/opt/host_workdir \
   $BUILDER_IMAGE ${REPO} ${BRANCH} amd64

# ARM64
docker run \
   --memory 24g \
   --cpus 6 \
   -it \
   --rm \
   --platform linux/arm64 \
   -v $WORKING_DIR:/mnt/host_workdir \
   $BUILDER_IMAGE ${REPO} ${BRANCH} arm64

cp -R $WORKING_DIR/output/common $SCRIPT_DIR/../../

cd $SCRIPT_DIR/../..
./mvnw package

